baseURL = 'http://dbt.yaelandgabi.org/'
languageCode = 'he-il'
defaultContentLanguage = 'he'
title = 'מיומנויות DBT'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[languages]
  [languages.he]
    disabled = false
    languageCode = 'he-il'
    languageDirection = 'rtl'
    languageName = 'hebrew' 
    title = 'מיומנויות DBT'
    weight = 0


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  custom_css = ["css/custom.css"]
  text_color = "mid-gray"
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-pink"
  recent_posts_number = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true


